plugin: nutanix.ncp.ntnx_prism_vm_inventory
nutanix_hostname: "{{ lookup('ansible.builtin.env', 'NUTANIX_HOSTNAME', default=undef()) }}" 
nutanix_username: "{{ lookup('ansible.builtin.env', 'NUTANIX_USERNAME', default=undef()) }}" 
nutanix_password: "{{ lookup('ansible.builtin.env', 'NUTANIX_PASSWORD', default=undef()) }}" 
validate_certs: false
data: { offset: 0, length: 1000 }
#groups:
#  group_1: "'<name_prefix>' in name"
#  group_2: "'<vm_name>'==name"
#keyed_groups:
#  - prefix: host
#    separator: ":"
#    key: ansible_host
